/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "G-Homa adapter settings": {                     "en": "G-Homa adapter settings",                         "de": "Einstellungen für G-Homa Adapter",                "ru": "G-Хома параметров адаптера ",                     "pt": "G-Homa as configurações do adaptador",            "nl": "G-Homa adapter instellingen",                     "fr": "G-Homa les paramètres de la carte",               "it": "G-Homa impostazioni della scheda di",             "es": "G-Homa configuración del adaptador",              "pl": "G-Homa ustawienia karty sieciowej ",              "zh-cn": "G-Homa设置适配器"},
    "If you have multiple network interfaces, you can select the correct one": {"en": "If you have multiple network interfaces, you can select the correct one", "de": "Wenn mehrere Netzwerkschnittstellen vorhanden sind, hier die richtige auswählen", "ru": "Если у вас несколько сетевых интерфейсов, вы можете выбрать правильный", "pt": "Se você tiver várias interfaces de rede, você pode selecionar o correto", "nl": "Als u meerdere netwerk interfaces, kunt u de juiste selecteren", "fr": "Si vous avez plusieurs interfaces réseau, vous pouvez sélectionner la bonne", "it": "Se si dispone di più interfacce di rete, è possibile selezionare quello corretto", "es": "Si tiene varias interfaces de red, usted puede elegir el correcto", "pl": "Jeśli masz kilka interfejsów sieciowych, można wybrać odpowiedni", "zh-cn": "如果你有多个网络接口，可以选择正确的"},
    "Manage devices": {                              "en": "Manage devices",                                  "de": "Geräte verwalten",                                "ru": "Управление устройствами",                         "pt": "Gerir dispositivos",                              "nl": "Apparaten beheren",                               "fr": "Gérer les périphériques",                         "it": "Gestire i dispositivi",                           "es": "Gestionar los dispositivos de",                   "pl": "Zarządzanie urządzeniami",                        "zh-cn": "管理设备"},
    "Network Interface:": {                          "en": "Network Interface:",                              "de": "Netzwerkschnittstelle:",                          "ru": "Сетевой Интерфейс:",                              "pt": "Interface De Rede:",                              "nl": "- Netwerk Interface:",                            "fr": "Interface Réseau:",                               "it": "Interfaccia Di Rete:",                            "es": "Interfaz De Red:",                                "pl": "Interfejs Sieciowy:",                             "zh-cn": "网络界面："},
    "Please enter the WiFi key!": {                  "en": "Please enter the WiFi key!",                      "de": "Bitte den WLAN-Schlüssel eingeben!",              "ru": "Пожалуйста, введите ключ WiFi!",                  "pt": "Por favor, digite a chave WiFi!",                 "nl": "Voer de WiFi-stick!",                             "fr": "Veuillez entrer la clé WiFi!",                    "it": "Si prega di inserire la chiavetta WiFi!",         "es": "Por favor, introduzca la clave WiFi!",            "pl": "Proszę, wpisz klucz WiFi!",                       "zh-cn": "请输入无线钥匙!"},
    "Settings": {                                    "en": "Settings",                                        "de": "Einstellungen",                                   "ru": "Параметры",                                       "pt": "Definições",                                      "nl": "Instellingen",                                    "fr": "Paramètres",                                      "it": "Impostazioni",                                    "es": "Configuración",                                   "pl": "Parametry",                                       "zh-cn": "设置"},
    "This is necessary to include new devices into the network": {"en": "This is necessary to include new devices into the network", "de": "Dies wird benötigt, um neue Geräte ins Netzwerk einzubinden", "ru": "Это необходимо для включения новых устройств в сеть", "pt": "Isto é necessário para incluir novos dispositivos na rede", "nl": "Dit is nodig om nieuwe apparaten in het netwerk", "fr": "Cela est nécessaire pour inclure de nouveaux dispositifs dans le réseau", "it": "Questo è necessario per includere i nuovi dispositivi in rete", "es": "Esto es necesario para incluir nuevos dispositivos en la red", "pl": "Jest to konieczne w celu włączenia nowych urządzeń w sieci", "zh-cn": "这是必要的，包括新的设备进入的网络"},
    "WiFi key:": {                                   "en": "WiFi key:",                                       "de": "WLAN-Passwort:",                                  "ru": "Ключ WiFi:",                                      "pt": "Wi-fi-chave:",                                    "nl": "WiFi-sleutel:",                                   "fr": "Clé WiFi:",                                       "it": "WiFi key:",                                       "es": "WiFi key:",                                       "pl": "Klucz WiFi:",                                     "zh-cn": "无线的关键："},
    "add device": {                                  "en": "add device",                                      "de": "Gerät hinzufügen",                                "ru": "добавить устройство",                             "pt": "adicionar dispositivo",                           "nl": "apparaat toevoegen",                              "fr": "ajouter un périphérique",                         "it": "aggiungi dispositivo",                            "es": "añadir dispositivo",                              "pl": "dodaj urządzenie",                                "zh-cn": "添加设备"},
    "on save adapter restarts with new config immediately": {"en": "on save adapter restarts with new config immediately", "de": "Beim Speichern von Einstellungen wird der Adapter sofort neu gestartet.", "ru": "Ñðàçó ïîñëå ñîõðàíåíèÿ íàñòðîåê äðàéâåð ïåðåçàïóñòèòüñÿ ñ íîâûìè çíà÷åíèÿìè", "pt": "em salvar adaptador reinicia com nova configuração e imediatamente", "nl": "op bespaar adapter opnieuw met nieuwe config onmiddellijk", "fr": "sur enregistrer l'adaptateur redémarre avec la nouvelle configuration, immédiatement", "it": "salva adattatore riavvia con la nuova config immediatamente", "es": "en guardar adaptador se reinicia con la nueva config de inmediato", "pl": "zapisz ponownym uruchomieniu zasilacza z nowy konfig raz", "zh-cn": "在保存适配器重新启动与新的配置立即"},
    "please wait...": {                              "en": "please wait...",                                  "de": "Bitte warten...",                                 "ru": "пожалуйста, подождите...",                        "pt": "por favor aguarde...",                            "nl": "please wait...",                                  "fr": "merci de patienter...",                           "it": "si prega di attendere...",                        "es": "por favor, espere...",                            "pl": "proszę czekać...",                                "zh-cn": "请等等..."},
};